spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    open-in-view: false
  mvc:
    format:
      date: dd/MM/yyyy
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off

  thymeleaf:
    check-template: false
    check-template-location: false
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
          jwk-set-uri: https://${AUTH0_DOMAIN}/.well-known/jwks.json
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        oauth2: DEBUG
    com:
      okta: DEBUG
      auth0: DEBUG

app:
  cors:
    allowed_origins: ${ALLOWED_ORIGINS}

  auth0:
    user_info_url: ${AUTH0_USER_INFO_URL}